### ISSUE TITLE
java.lang.NullPointerException: validateProjectPath(...) must not be null

### ISSUE THREAD

**Issue by pileskyd** [KartanHQ/intellij-nuxtjs#246]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
* Java: JetBrains s.r.o. 17.0.7
* OS: Mac OS X aarch64
* IDE: WebStorm 2023.2
* Version: 2.0.2

**Additional context**

**Stacktrace**
null

**Comment by nekofar** [comment]
Thank you for bringing the issue to our attention. I am pleased to inform you that it has been addressed and resolved in version v2.0.6.
