### ISSUE TITLE
java.lang.NullPointerException: validateProjectPath(...) must not be null

### ISSUE THREAD

**Issue by hasunnilupul** [KartanHQ/intellij-nuxtjs#250]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
* Java: JetBrains s.r.o. 17.0.7
* OS: Windows 10 amd64
* IDE: WebStorm 2023.1.4
* Version: 2.0.2

**Additional context**

**Stacktrace**
null

**Comment by nekofar** [comment]
Duplicate of #246
