### ISSUE TITLE
Not compatible with Webstorm 2022.2 (ide build 222.*)

### ISSUE THREAD

**Issue by Vinccool96** [KartanHQ/intellij-nuxtjs#82]

**Comment by MartinX3** [comment]
Thank you but sadly there is still no new release on this repo or the jetbrains plugin repo.

**Comment by nekofar** [comment]
> Thank you but sadly there is still no new release on this repo or the jetbrains plugin repo.

It's available in release section and would be on marketplace in couple of hours.
